// Code generated by goctl. DO NOT EDIT.
// Source: post.proto

package server

import (
	"context"

	"github.com/seth-shi/go-zero-testing-example/app/post/rpc/internal/logic"
	"github.com/seth-shi/go-zero-testing-example/app/post/rpc/internal/svc"
	"github.com/seth-shi/go-zero-testing-example/app/post/rpc/post"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServer) Get(ctx context.Context, in *post.PostRequest) (*post.PostResponse, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
