// Code generated by goctl. DO NOT EDIT.
// Source: id.proto

package server

import (
	"context"

	"github.com/seth-shi/go-zero-testing-example/app/id/rpc/id"
	"github.com/seth-shi/go-zero-testing-example/app/id/rpc/internal/logic"
	"github.com/seth-shi/go-zero-testing-example/app/id/rpc/internal/svc"
)

type IdServer struct {
	svcCtx *svc.ServiceContext
	id.UnimplementedIdServer
}

func NewIdServer(svcCtx *svc.ServiceContext) *IdServer {
	return &IdServer{
		svcCtx: svcCtx,
	}
}

func (s *IdServer) Get(ctx context.Context, in *id.IdRequest) (*id.IdResponse, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
