// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePost = "posts"

// Post mapped from table <posts>
type Post struct {
	ID        uint64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey" json:"id"`
	Title     *string    `gorm:"column:title;type:varchar(255)" json:"title"`
	Content   *string    `gorm:"column:content;type:text" json:"content"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;autoCreateTime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;autoUpdateTime" json:"updated_at"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
